name: MCLoreBot
version: '2.0.0'
main: org.github.heartofchaos.Main
api-version: 1.13
authors: [ HeartOfChaos ]
description: A plugin that allows you to import and export lore text to and from discord.
commands:
  dlore:
    description: Used for Discord Lore commands.
permissions:
  mclore.*:
    description: Gives access to all MCLoreBot commands.
  mclore.start:
    description: Gives permission to the command to start the bot.
  mclore.stop:
    description: Gives permission to the command to stop the bot.
  mclore.token:
    description: Gives permission to set the bot's token.
  mclore.link:
    description: Gives permission to link your account to a discord account.
  mclore.gui:
    description: Gives permission to open the lore gui.
  mclore.clear:
    description: Gives permission to clear your lore queue of all items.
  mclore.set:
    description: Gives permission to set the lore of the item you're holding to your latest lore.
  mclore.dlore:
    description: Gives permission to use the main /dlore command.
  mclore.send:
    description: Gives permission to send lore to your dms using /dlore send.